-- Crear BD (usa una collation compatible con MySQL 5.7+/8.x universal)
CREATE DATABASE IF NOT EXISTS clientesCI
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;


USE clientesCI;


-- Tabla principal
CREATE TABLE IF NOT EXISTS tiempos (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
CORRERIA VARCHAR(50) NULL,
INSTALACION VARCHAR(100) NULL,
CLIENTE VARCHAR(150) NULL,
MEDIDOR VARCHAR(50) NULL,
LECTOR VARCHAR(100) NULL,
ANO SMALLINT NULL,
MES TINYINT NULL,
CICLO INT NULL,
ZONA VARCHAR(50) NULL,
FECHAULTLABOR DATE NULL,
HORAULTLABOR TIME NULL,
CODTAREA VARCHAR(50) NULL,
LECTURA_ACT INT NULL,
PRIMARY KEY (id),
KEY idx_anomes (ANO, MES),
KEY idx_cliente (CLIENTE(50)),
KEY idx_medidor (MEDIDOR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;