CREATE TABLE observacionesLectura (
    CODIGO_NUMERICO INT,
    OBSERVACION VARCHAR(100),
    COD_HOMOLOGADO VARCHAR(10),
    OPCIONES_POSIBLES VARCHAR(200),
    ACLARACION VARCHAR(200),
    TIPO_OBSERVACION VARCHAR(50)
);