-- Tabla de clientes (con CLIENTE_ID como bigint para coincidir con tiempos)
CREATE TABLE clientes (
    CLIENTE_ID BIGINT(20) PRIMARY KEY,
    NOMBRE VARCHAR(75),
    NIT VARCHAR(20),
    TELEFONO VARCHAR(20),
    TELEFONO_CELULAR VARCHAR(20),
    TELEFONO_REGISTRO VARCHAR(20),
    CORREO TEXT,
    ZONA VARCHAR(10),
    CICLO VARCHAR(10),
    RUTA_REPARTO VARCHAR(50),
    RUTA_LECTURA VARCHAR(20),
    SECCION VARCHAR(10),
    ORDEN VARCHAR(10),
    MUNICIPIO VARCHAR(10),
    DESC_MUNICIPIO VARCHAR(100),
    BARRIO VARCHAR(100),
    DIRECCION TEXT,
    CENTRO_POBLADO VARCHAR(100),
    FICHA_CATASTRAL VARCHAR(50),
    MATRICULA_INMOBILIARIA VARCHAR(50),
    ESTRATO INT(11),
    CLASE_SERVICIO VARCHAR(50),
    NUMERO_MEDIDOR VARCHAR(50),
    MARCA_MEDIDOR VARCHAR(50),
    TECNOLOGIA_MEDIDOR VARCHAR(10),
    D_TECNOLOGIA_MEDIDOR VARCHAR(50),
    TIPO_REGISTRADOR VARCHAR(10),
    D_TIPO_REGISTRADOR VARCHAR(50),
    UBICACION VARCHAR(50),
    GPS_LATITUD DECIMAL(10,6),
    GPS_LONGITUD DECIMAL(11,8),
    GPS_ALTITUD INT(11),
    ESTADO_CLIENTE TINYINT(4),
    TRANSFORMADOR VARCHAR(20),
    ALIMENTADOR VARCHAR(20),
    CODIGO_EXTERNO VARCHAR(50),
    COD_CIU VARCHAR(100)
) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Tabla TipoFacturacion (con CLIENTE_ID como bigint)
CREATE TABLE TipoFacturacion (
    REGIONAL VARCHAR(10),
    DEPARTAMENTO VARCHAR(100),
    MUNICIPIO VARCHAR(100),
    BARRIO VARCHAR(100),
    CLASE_SERVICIO VARCHAR(50),
    COD_TARIFA VARCHAR(10),
    TARIFA VARCHAR(100),
    ESTRATO INT(11),
    AREA VARCHAR(20),
    CICLO TEXT,
    CLIENTE_ID BIGINT(20),
    NOMBRE VARCHAR(255),
    DIRECCION TEXT,
    DIRECCION_MEDIO TEXT,
    MUNICIPIO_POSTAL VARCHAR(100),
    CORREO_ELECTRONICO VARCHAR(255),
    TIPO_FACTURACION VARCHAR(100),
    AUTORIZA_DATOS VARCHAR(20),
    TIPO_RECIBO TEXT,
    USER_SISTEMA VARCHAR(50),
    FECHA_SISTEMA TEXT,
    CAMBIO_DATOS TEXT,
    FOREIGN KEY (CLIENTE_ID) REFERENCES clientes(CLIENTE_ID)
) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Agregar clave foránea a la tabla tiempos existente
ALTER TABLE tiempos
ADD CONSTRAINT fk_tiempos_cliente
FOREIGN KEY (cliente) REFERENCES clientes(CLIENTE_ID);