export const TABLE_REVISIONES = 'clientes_servicios';

export const COLUMNS_REVISIONES = [
  'CLIENTE_ID', 'NOMBRE', 'DIRECCION', 'MUNICIPIO', 'CICLO', 'CLASE_SERVICIO', 'TARIFA', 'ESTRATO',
  'ESTADO_SUMINISTRO', 'RUTA_LECTURA',
  'SERIE_R', 'MARCA_R', 'FACTOR_MUL_R', 'UBICACION_R', 'PROPIEDAD_R', 'ACCION_MEDIDOR_R', 'LECTURA_R', 'OBS_CONSUMO_R', 'CAUSA_NO_LECTURA_R',
  'SERIE_I', 'MARCA_I', 'FACTOR_MUL_I', 'UBICACION_I', 'PROPIEDAD_I', 'ACCION_MEDIDOR_I', 'LECTURA_I', 'OBS_CONSUMO_I', 'CAUSA_NO_LECTURA_I',
  'SERIE_T', 'MARCA_T', 'FACTOR_MUL_T', 'UBICACION_T', 'PROPIEDAD_T', 'ACCION_MEDIDOR_T', 'LECTURA_T', 'OBS_CONSUMO_T', 'CAUSA_NO_LECTURA_T',
  'SERIE_X', 'MARCA_X', 'FACTOR_MUL_X', 'UBICACION_X', 'PROPIEDAD_X', 'ACCION_MEDIDOR_X', 'LECTURA_X', 'OBS_CONSUMO_X', 'CAUSA_NO_LECTURA_X',
  'NUMERO_REVISION', 'ESTADO_REVISION', 'TIPO_PROCESO', 'NUMERO_PROCESO', 'ESTADO_PROCESO', 'NUEVA', 'TIPO', 'D_TIPO', 'GRUPO_REV', 'MOTIVO', 'D_MOTIVO',
  'FECHA_SOLICITUD', 'FECHA_REVISION', 'FECHA_SISTEMA', 'REVISOR', 'D_REVISOR', 'GENERADO_POR', 'USER_SISTEMA',
  'IDESTADO', 'TERMINALDESCARGA', 'FECHAULTLABOR', 'CORRERIA', 'FECHAINICIOLABOR', 'FECHAFINJORNADA', 'OBSERVACION', 'D_OBSERVACION', 'OBSREVISION',
  'TRANSFORMADOR', 'PROGRAMA_DE_INGRESO'
];

export function buildInsertSQLRevisiones(batchLen) {
  const placeholdersOne = `(${COLUMNS_REVISIONES.map(() => '?').join(',')})`;
  const placeholdersAll = Array.from({ length: batchLen }).map(() => placeholdersOne).join(',');
  return `INSERT INTO ${TABLE_REVISIONES} (${COLUMNS_REVISIONES.join(',')}) VALUES ${placeholdersAll}`;
}
